package com.westchase.persistence.model;
// Generated Jun 29, 2009 7:29:18 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Category implements java.io.Serializable {

	private String categoryCode;
	private String categoryDesc;
	private Date inputDate;
	private Set<PhoneBookCategory> personCategories = new HashSet<PhoneBookCategory>(
			0);
//	private Set<PersonCategory> personCategories_1 = new HashSet<PersonCategory>(
//			0);

	public Category() {
	}

	public Category(String categoryCode) {
		this.categoryCode = categoryCode;
	}
	public Category(String categoryCode, String categoryDesc, Date inputDate,
			Set<PhoneBookCategory> personCategories) {
		this.categoryCode = categoryCode;
		this.categoryDesc = categoryDesc;
		this.inputDate = inputDate;
		this.personCategories = personCategories;
	}

	@Id
	@Column(name = "CategoryCode", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getCategoryCode() {
		return this.categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	@Column(name = "CategoryDesc", length = 40)
	@Length(max = 40)
	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InputDate", length = 19)
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "category")
	public Set<PhoneBookCategory> getPersonCategories() {
		return this.personCategories;
	}

	public void setPersonCategories(Set<PhoneBookCategory> personCategories) {
		this.personCategories = personCategories;
	}
//	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "category")
//	public Set<PersonCategory> getPersonCategories_1() {
//		return this.personCategories_1;
//	}
//
//	public void setPersonCategories_1(Set<PersonCategory> personCategories_1) {
//		this.personCategories_1 = personCategories_1;
//	}

}
