package com.westchase.persistence.model;

// Generated Nov 14, 2012 9:29:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

/**
 * Citizen generated by hbm2java
 */
@Entity
@Table(name = "citizen")
public class Citizen implements java.io.Serializable {

	private Long id;
	private String firstName;
	private String middleName;
	private String lastName;
	private Integer txDl;
	private String organization;
	private String streetAddress;
	private String zipCode;
	private Set<PatrolActivityDetailCitizen> patrolActivityDetailCitizens = new HashSet<PatrolActivityDetailCitizen>(0);

	public Citizen() {
		super();
	}

	public Citizen(Long id) {
		this();
		this.id = id;
	}

	public Citizen(Long id, String firstName, String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Citizen(Long id, String firstName, String middleName, String lastName, Integer txDl,
			Set<PatrolActivityDetailCitizen> patrolActivityDetailCitizens) {
		this.id = id;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.txDl = txDl;
		this.patrolActivityDetailCitizens = patrolActivityDetailCitizens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "tx_dl")
	public Integer getTxDl() {
		return this.txDl;
	}

	public void setTxDl(Integer txDl) {
		this.txDl = txDl;
	}

	@Column(name = "organization")
	public String getOrganization() {
		return organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	@Column(name = "street_address")
	public String getStreetAddress() {
		return streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "zip_code")
	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "citizen")
	public Set<PatrolActivityDetailCitizen> getPatrolActivityDetailCitizens() {
		return this.patrolActivityDetailCitizens;
	}

	public void setPatrolActivityDetailCitizens(Set<PatrolActivityDetailCitizen> patrolActivityDetailCitizens) {
		this.patrolActivityDetailCitizens = patrolActivityDetailCitizens;
	}
	
	@Transient
	public String getSummaryValue() {
		String summary = firstName;
		if (StringUtils.isNotBlank(middleName)) {
			summary += " " + middleName;
		}
		summary += " " + lastName;
		if (txDl != null && txDl.intValue() < 0) {
			summary += " (" + StringUtils.leftPad(txDl.toString(), 8, '0') + ")";
		}
		return summary;
	}
	public void setSummaryValue(String summaryValue) {
	}

}
