package com.westchase.persistence.model;

// Generated Sep 5, 2010 4:55:55 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmuDevsite generated by hbm2java
 */
@Entity
@Table(name = "cmu_devsite")
public class CmuDevsite implements java.io.Serializable {

	private Integer id;
	private Property property;
	private CmuQuarter cmuQuarter;
	private String completedBy;
	private Double siteSize;
	private String frontage;
	private String contact;
	private String company;
	private String phone;
	private String fax;
	private String email;
	private boolean divide;
	private String priceSqFt;
	private String restrictions;
	private String comments;
	private Date updated;
	private Date verified;

	public CmuDevsite() {
	}

	public CmuDevsite(Property property, CmuQuarter cmuQuarter, boolean divide, Date updated) {
		this.property = property;
		this.cmuQuarter = cmuQuarter;
		this.divide = divide;
		this.updated = updated;
	}

	public CmuDevsite(Property property, CmuQuarter cmuQuarter, String completedBy, Double siteSize, String frontage,
			String contact, String company, String phone, String fax, String email, boolean divide, String priceSqFt,
			String restrictions, String comments, Date updated, Date verified) {
		this.property = property;
		this.cmuQuarter = cmuQuarter;
		this.completedBy = completedBy;
		this.siteSize = siteSize;
		this.frontage = frontage;
		this.contact = contact;
		this.company = company;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.divide = divide;
		this.priceSqFt = priceSqFt;
		this.restrictions = restrictions;
		this.comments = comments;
		this.updated = updated;
		this.verified = verified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "property", nullable = false)
	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "quarter", nullable = false)
	public CmuQuarter getCmuQuarter() {
		return this.cmuQuarter;
	}

	public void setCmuQuarter(CmuQuarter cmuQuarter) {
		this.cmuQuarter = cmuQuarter;
	}

	@Column(name = "completed_by")
	public String getCompletedBy() {
		return this.completedBy;
	}

	public void setCompletedBy(String completedBy) {
		this.completedBy = completedBy;
	}

	@Column(name = "site_size", precision = 22, scale = 0)
	public Double getSiteSize() {
		return this.siteSize;
	}

	public void setSiteSize(Double siteSize) {
		this.siteSize = siteSize;
	}

	@Column(name = "frontage")
	public String getFrontage() {
		return this.frontage;
	}

	public void setFrontage(String frontage) {
		this.frontage = frontage;
	}

	@Column(name = "contact")
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "company")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "divide", nullable = false)
	public boolean isDivide() {
		return this.divide;
	}

	public void setDivide(boolean divide) {
		this.divide = divide;
	}

	@Column(name = "price_sq_ft", length = 20)
	public String getPriceSqFt() {
		return this.priceSqFt;
	}

	public void setPriceSqFt(String priceSqFt) {
		this.priceSqFt = priceSqFt;
	}

	@Column(name = "restrictions")
	public String getRestrictions() {
		return this.restrictions;
	}

	public void setRestrictions(String restrictions) {
		this.restrictions = restrictions;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = true, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "verified", nullable = true, length = 19)
	public Date getVerified() {
		return this.verified;
	}

	public void setVerified(Date verified) {
		this.verified = verified;
	}

}
