package com.westchase.persistence.model;

// Generated Sep 5, 2010 4:55:55 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmuHotel generated by hbm2java
 */
@Entity
@Table(name = "cmu_hotel")
public class CmuHotel implements java.io.Serializable {

	private Integer id;
	private Property property;
	private CmuQuarter cmuQuarter;
	private String completedBy;
	private String generalMgr;
	private String generalMgrEmail;
	private String generalMgrPhone;
	private Double occupancy;
	private String comments;
	private Date updated;
	private Date verified;

	public CmuHotel() {
	}

	public CmuHotel(Property property, CmuQuarter cmuQuarter, Date updated) {
		this.property = property;
		this.cmuQuarter = cmuQuarter;
		this.updated = updated;
	}

	public CmuHotel(Property property, CmuQuarter cmuQuarter, String completedBy, String generalMgr,
			String generalMgrEmail, String generalMgrPhone, Double occupancy, String comments, Date updated,
			Date verified) {
		this.property = property;
		this.cmuQuarter = cmuQuarter;
		this.completedBy = completedBy;
		this.generalMgr = generalMgr;
		this.generalMgrEmail = generalMgrEmail;
		this.generalMgrPhone = generalMgrPhone;
		this.occupancy = occupancy;
		this.comments = comments;
		this.updated = updated;
		this.verified = verified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "property", nullable = false)
	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "quarter", nullable = false)
	public CmuQuarter getCmuQuarter() {
		return this.cmuQuarter;
	}

	public void setCmuQuarter(CmuQuarter cmuQuarter) {
		this.cmuQuarter = cmuQuarter;
	}

	@Column(name = "completed_by")
	public String getCompletedBy() {
		return this.completedBy;
	}

	public void setCompletedBy(String completedBy) {
		this.completedBy = completedBy;
	}

	@Column(name = "general_mgr")
	public String getGeneralMgr() {
		return this.generalMgr;
	}

	public void setGeneralMgr(String generalMgr) {
		this.generalMgr = generalMgr;
	}

	@Column(name = "general_mgr_email")
	public String getGeneralMgrEmail() {
		return this.generalMgrEmail;
	}

	public void setGeneralMgrEmail(String generalMgrEmail) {
		this.generalMgrEmail = generalMgrEmail;
	}

	@Column(name = "general_mgr_phone")
	public String getGeneralMgrPhone() {
		return this.generalMgrPhone;
	}

	public void setGeneralMgrPhone(String generalMgrPhone) {
		this.generalMgrPhone = generalMgrPhone;
	}

	@Column(name = "occupancy", precision = 22, scale = 0)
	public Double getOccupancy() {
		return this.occupancy;
	}

	public void setOccupancy(Double occupancy) {
		this.occupancy = occupancy;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = true, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "verified", nullable = true, length = 19)
	public Date getVerified() {
		return this.verified;
	}

	public void setVerified(Date verified) {
		this.verified = verified;
	}

}
