package com.westchase.persistence.model;

// Generated Sep 5, 2010 4:55:55 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CmuTransactionType generated by hbm2java
 */
@Entity
@Table(name = "cmu_transaction_type")
public class CmuTransactionType implements java.io.Serializable {

	private int id;
	private String description;
	private Set<CmuLease> cmuLeases = new HashSet<CmuLease>(0);

	public CmuTransactionType() {
	}

	public CmuTransactionType(int id) {
		this();
		this.id = id;
	}

	public CmuTransactionType(String description) {
		this.description = description;
	}

	public CmuTransactionType(String description, Set<CmuLease> cmuLeases) {
		this.description = description;
		this.cmuLeases = cmuLeases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cmuTransactionType")
	public Set<CmuLease> getCmuLeases() {
		return this.cmuLeases;
	}

	public void setCmuLeases(Set<CmuLease> cmuLeases) {
		this.cmuLeases = cmuLeases;
	}

}
