package com.westchase.persistence.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "company_code")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class CompanyCode implements java.io.Serializable {

	private String code;
	private String name;

	public CompanyCode() {
		super();
	}

	public CompanyCode(String code, String name) {
		this();
		setCode(code);
		setName(name);
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 100)
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
