package com.westchase.persistence.model;

// Generated Oct 6, 2009 7:14:31 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailTemplate generated by hbm2java
 */
@Entity
@Table(name = "email_template")
public class EmailTemplate implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private String subject;
	private String message;
	private byte[] attachment;
	private String attachmentName;
	private Date createDate;
	private Set<SentEmail> sentEmails = new HashSet<SentEmail>(0);

	public EmailTemplate() {
	}


	public EmailTemplate(Integer id) {
		this.id = id;
	}
	public EmailTemplate(Employee employee, String subject, String message, byte[] attachment, Date createDate) {
		this.employee = employee;
		this.subject = subject;
		this.message = message;
		this.attachment = attachment;
		this.createDate = createDate;
	}

	public EmailTemplate(Employee employee, String subject, String message, byte[] attachment, Date createDate, String attachmentName,
			Set<SentEmail> sentEmails) {
		this.employee = employee;
		this.subject = subject;
		this.message = message;
		this.attachment = attachment;
		this.attachmentName = attachmentName;
		this.createDate = createDate;
		this.sentEmails = sentEmails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "subject", nullable = false, length = 1000)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "attachment", nullable = true)
	public byte[] getAttachment() {
		return this.attachment;
	}

	public void setAttachment(byte[] attachment) {
		this.attachment = attachment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emailTemplate")
	public Set<SentEmail> getSentEmails() {
		return this.sentEmails;
	}

	public void setSentEmails(Set<SentEmail> sentEmails) {
		this.sentEmails = sentEmails;
	}

	@Column(name = "attachment_name", nullable = true)
	public String getAttachmentName() {
		return this.attachmentName;
	}

	public void setAttachmentName(String attachmentName) {
		this.attachmentName = attachmentName;
	}

}
