package com.westchase.persistence.model;
// Generated Jun 29, 2009 7:29:18 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Hcad generated by hbm2java
 */
@Entity
@Table(name = "hcad")
public class Hcad implements java.io.Serializable {

	private String account;
	private Short taxYear;
	private String ownerName;
	private String ownerAddress1;
	private String ownerAddress2;
	private String ownerAddress3;
	private String cityState;
	private String ownerZip;
	private String propIdentifier;
	private String propDescription1;
	private String propDescription2;
	private String propDescription3;
	private String propDescription4;
	private BigDecimal acres;
	private Short squareFeet;
	private String locStreetNum;
	private String locStreetName;
	private String locBuildingCode;
	private String locSuiteCode;
	private String locZip;
	private String jurCode1;
	private String jurCode2;
	private String jurCode3;
	private String jurCode4;
	private String jurCode5;
	private String jurCode6;
	private String jurCode7;
	private String jurCode8;
	private String jurCode9;
	private String jurCode10;
	private String noticeFlag;
	private String noticeDate;
	private String ardate;
	private String hitsDate;
	private Short hitsValue;
	private String multiAgentFlag;
	private String parcelNumber;
	private String stateCatCode;
	private String pptcode;
	private String siccode;
	private String iccode;
	private String regionCenter;
	private String mapFacet;
	private Short persPropValue;
	private Integer landValue;
	private Integer improvementsValue;
	private Integer productivityValue;
	private String productivityType;
	private String specialCode;
	private String hmstdxmptcode;
	private Short pctHmstdvalue;
	private Short vetPct1;
	private Short vetPct2;
	private String spclxmptcode;
	private Integer spclxmptvalue;
	private String spclxmptpct;
	private String htsflag;
	private String ptsflag;
	private String bpsflag;
	private String realPropRef;
	private Integer exemptValue;
	private Integer taxableValue;
	private String adjcadcode;
	private String adjcadacct;
	private Short adjcadlandValue;
	private Short adjcadimprvalue;
	private Short adjcadpersValue;
	private String nbhd;
	private String luc;
	private String agentNum;
	private String agentAddr1;
	private Short mktlandValue;
	private Short mktimprvalue;
	private String rendFlag;
	private Short camamktValue;
	private String lstvisitDate;
	private String actualPurdate;
	private String effectPurdate;

	public Hcad() {
	}

	public Hcad(String account) {
		this.account = account;
	}
	public Hcad(String account, Short taxYear, String ownerName,
			String ownerAddress1, String ownerAddress2, String ownerAddress3,
			String cityState, String ownerZip, String propIdentifier,
			String propDescription1, String propDescription2,
			String propDescription3, String propDescription4, BigDecimal acres,
			Short squareFeet, String locStreetNum, String locStreetName,
			String locBuildingCode, String locSuiteCode, String locZip,
			String jurCode1, String jurCode2, String jurCode3, String jurCode4,
			String jurCode5, String jurCode6, String jurCode7, String jurCode8,
			String jurCode9, String jurCode10, String noticeFlag,
			String noticeDate, String ardate, String hitsDate, Short hitsValue,
			String multiAgentFlag, String parcelNumber, String stateCatCode,
			String pptcode, String siccode, String iccode, String regionCenter,
			String mapFacet, Short persPropValue, Integer landValue,
			Integer improvementsValue, Integer productivityValue,
			String productivityType, String specialCode, String hmstdxmptcode,
			Short pctHmstdvalue, Short vetPct1, Short vetPct2,
			String spclxmptcode, Integer spclxmptvalue, String spclxmptpct,
			String htsflag, String ptsflag, String bpsflag, String realPropRef,
			Integer exemptValue, Integer taxableValue, String adjcadcode,
			String adjcadacct, Short adjcadlandValue, Short adjcadimprvalue,
			Short adjcadpersValue, String nbhd, String luc, String agentNum,
			String agentAddr1, Short mktlandValue, Short mktimprvalue,
			String rendFlag, Short camamktValue, String lstvisitDate,
			String actualPurdate, String effectPurdate) {
		this.account = account;
		this.taxYear = taxYear;
		this.ownerName = ownerName;
		this.ownerAddress1 = ownerAddress1;
		this.ownerAddress2 = ownerAddress2;
		this.ownerAddress3 = ownerAddress3;
		this.cityState = cityState;
		this.ownerZip = ownerZip;
		this.propIdentifier = propIdentifier;
		this.propDescription1 = propDescription1;
		this.propDescription2 = propDescription2;
		this.propDescription3 = propDescription3;
		this.propDescription4 = propDescription4;
		this.acres = acres;
		this.squareFeet = squareFeet;
		this.locStreetNum = locStreetNum;
		this.locStreetName = locStreetName;
		this.locBuildingCode = locBuildingCode;
		this.locSuiteCode = locSuiteCode;
		this.locZip = locZip;
		this.jurCode1 = jurCode1;
		this.jurCode2 = jurCode2;
		this.jurCode3 = jurCode3;
		this.jurCode4 = jurCode4;
		this.jurCode5 = jurCode5;
		this.jurCode6 = jurCode6;
		this.jurCode7 = jurCode7;
		this.jurCode8 = jurCode8;
		this.jurCode9 = jurCode9;
		this.jurCode10 = jurCode10;
		this.noticeFlag = noticeFlag;
		this.noticeDate = noticeDate;
		this.ardate = ardate;
		this.hitsDate = hitsDate;
		this.hitsValue = hitsValue;
		this.multiAgentFlag = multiAgentFlag;
		this.parcelNumber = parcelNumber;
		this.stateCatCode = stateCatCode;
		this.pptcode = pptcode;
		this.siccode = siccode;
		this.iccode = iccode;
		this.regionCenter = regionCenter;
		this.mapFacet = mapFacet;
		this.persPropValue = persPropValue;
		this.landValue = landValue;
		this.improvementsValue = improvementsValue;
		this.productivityValue = productivityValue;
		this.productivityType = productivityType;
		this.specialCode = specialCode;
		this.hmstdxmptcode = hmstdxmptcode;
		this.pctHmstdvalue = pctHmstdvalue;
		this.vetPct1 = vetPct1;
		this.vetPct2 = vetPct2;
		this.spclxmptcode = spclxmptcode;
		this.spclxmptvalue = spclxmptvalue;
		this.spclxmptpct = spclxmptpct;
		this.htsflag = htsflag;
		this.ptsflag = ptsflag;
		this.bpsflag = bpsflag;
		this.realPropRef = realPropRef;
		this.exemptValue = exemptValue;
		this.taxableValue = taxableValue;
		this.adjcadcode = adjcadcode;
		this.adjcadacct = adjcadacct;
		this.adjcadlandValue = adjcadlandValue;
		this.adjcadimprvalue = adjcadimprvalue;
		this.adjcadpersValue = adjcadpersValue;
		this.nbhd = nbhd;
		this.luc = luc;
		this.agentNum = agentNum;
		this.agentAddr1 = agentAddr1;
		this.mktlandValue = mktlandValue;
		this.mktimprvalue = mktimprvalue;
		this.rendFlag = rendFlag;
		this.camamktValue = camamktValue;
		this.lstvisitDate = lstvisitDate;
		this.actualPurdate = actualPurdate;
		this.effectPurdate = effectPurdate;
	}

	@Id
	@Column(name = "account", unique = true, nullable = false, length = 13)
	@NotNull
	@Length(max = 13)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "TaxYear")
	public Short getTaxYear() {
		return this.taxYear;
	}

	public void setTaxYear(Short taxYear) {
		this.taxYear = taxYear;
	}

	@Column(name = "OwnerName", length = 26)
	@Length(max = 26)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "OwnerAddress1", length = 26)
	@Length(max = 26)
	public String getOwnerAddress1() {
		return this.ownerAddress1;
	}

	public void setOwnerAddress1(String ownerAddress1) {
		this.ownerAddress1 = ownerAddress1;
	}

	@Column(name = "OwnerAddress2", length = 26)
	@Length(max = 26)
	public String getOwnerAddress2() {
		return this.ownerAddress2;
	}

	public void setOwnerAddress2(String ownerAddress2) {
		this.ownerAddress2 = ownerAddress2;
	}

	@Column(name = "OwnerAddress3", length = 26)
	@Length(max = 26)
	public String getOwnerAddress3() {
		return this.ownerAddress3;
	}

	public void setOwnerAddress3(String ownerAddress3) {
		this.ownerAddress3 = ownerAddress3;
	}

	@Column(name = "CityState", length = 26)
	@Length(max = 26)
	public String getCityState() {
		return this.cityState;
	}

	public void setCityState(String cityState) {
		this.cityState = cityState;
	}

	@Column(name = "OwnerZip", length = 9)
	@Length(max = 9)
	public String getOwnerZip() {
		return this.ownerZip;
	}

	public void setOwnerZip(String ownerZip) {
		this.ownerZip = ownerZip;
	}

	@Column(name = "PropIdentifier", length = 20)
	@Length(max = 20)
	public String getPropIdentifier() {
		return this.propIdentifier;
	}

	public void setPropIdentifier(String propIdentifier) {
		this.propIdentifier = propIdentifier;
	}

	@Column(name = "PropDescription1", length = 30)
	@Length(max = 30)
	public String getPropDescription1() {
		return this.propDescription1;
	}

	public void setPropDescription1(String propDescription1) {
		this.propDescription1 = propDescription1;
	}

	@Column(name = "PropDescription2", length = 30)
	@Length(max = 30)
	public String getPropDescription2() {
		return this.propDescription2;
	}

	public void setPropDescription2(String propDescription2) {
		this.propDescription2 = propDescription2;
	}

	@Column(name = "PropDescription3", length = 30)
	@Length(max = 30)
	public String getPropDescription3() {
		return this.propDescription3;
	}

	public void setPropDescription3(String propDescription3) {
		this.propDescription3 = propDescription3;
	}

	@Column(name = "PropDescription4", length = 30)
	@Length(max = 30)
	public String getPropDescription4() {
		return this.propDescription4;
	}

	public void setPropDescription4(String propDescription4) {
		this.propDescription4 = propDescription4;
	}

	@Column(name = "Acres", precision = 18, scale = 4)
	public BigDecimal getAcres() {
		return this.acres;
	}

	public void setAcres(BigDecimal acres) {
		this.acres = acres;
	}

	@Column(name = "SquareFeet")
	public Short getSquareFeet() {
		return this.squareFeet;
	}

	public void setSquareFeet(Short squareFeet) {
		this.squareFeet = squareFeet;
	}

	@Column(name = "LocStreetNum", length = 5)
	@Length(max = 5)
	public String getLocStreetNum() {
		return this.locStreetNum;
	}

	public void setLocStreetNum(String locStreetNum) {
		this.locStreetNum = locStreetNum;
	}

	@Column(name = "LocStreetName", length = 30)
	@Length(max = 30)
	public String getLocStreetName() {
		return this.locStreetName;
	}

	public void setLocStreetName(String locStreetName) {
		this.locStreetName = locStreetName;
	}

	@Column(name = "LocBuildingCode", length = 7)
	@Length(max = 7)
	public String getLocBuildingCode() {
		return this.locBuildingCode;
	}

	public void setLocBuildingCode(String locBuildingCode) {
		this.locBuildingCode = locBuildingCode;
	}

	@Column(name = "LocSuiteCode", length = 6)
	@Length(max = 6)
	public String getLocSuiteCode() {
		return this.locSuiteCode;
	}

	public void setLocSuiteCode(String locSuiteCode) {
		this.locSuiteCode = locSuiteCode;
	}

	@Column(name = "LocZip", length = 50)
	@Length(max = 50)
	public String getLocZip() {
		return this.locZip;
	}

	public void setLocZip(String locZip) {
		this.locZip = locZip;
	}

	@Column(name = "JurCode1", length = 3)
	@Length(max = 3)
	public String getJurCode1() {
		return this.jurCode1;
	}

	public void setJurCode1(String jurCode1) {
		this.jurCode1 = jurCode1;
	}

	@Column(name = "JurCode2", length = 3)
	@Length(max = 3)
	public String getJurCode2() {
		return this.jurCode2;
	}

	public void setJurCode2(String jurCode2) {
		this.jurCode2 = jurCode2;
	}

	@Column(name = "JurCode3", length = 3)
	@Length(max = 3)
	public String getJurCode3() {
		return this.jurCode3;
	}

	public void setJurCode3(String jurCode3) {
		this.jurCode3 = jurCode3;
	}

	@Column(name = "JurCode4", length = 3)
	@Length(max = 3)
	public String getJurCode4() {
		return this.jurCode4;
	}

	public void setJurCode4(String jurCode4) {
		this.jurCode4 = jurCode4;
	}

	@Column(name = "JurCode5", length = 3)
	@Length(max = 3)
	public String getJurCode5() {
		return this.jurCode5;
	}

	public void setJurCode5(String jurCode5) {
		this.jurCode5 = jurCode5;
	}

	@Column(name = "JurCode6", length = 3)
	@Length(max = 3)
	public String getJurCode6() {
		return this.jurCode6;
	}

	public void setJurCode6(String jurCode6) {
		this.jurCode6 = jurCode6;
	}

	@Column(name = "JurCode7", length = 3)
	@Length(max = 3)
	public String getJurCode7() {
		return this.jurCode7;
	}

	public void setJurCode7(String jurCode7) {
		this.jurCode7 = jurCode7;
	}

	@Column(name = "JurCode8", length = 3)
	@Length(max = 3)
	public String getJurCode8() {
		return this.jurCode8;
	}

	public void setJurCode8(String jurCode8) {
		this.jurCode8 = jurCode8;
	}

	@Column(name = "JurCode9", length = 3)
	@Length(max = 3)
	public String getJurCode9() {
		return this.jurCode9;
	}

	public void setJurCode9(String jurCode9) {
		this.jurCode9 = jurCode9;
	}

	@Column(name = "JurCode10", length = 3)
	@Length(max = 3)
	public String getJurCode10() {
		return this.jurCode10;
	}

	public void setJurCode10(String jurCode10) {
		this.jurCode10 = jurCode10;
	}

	@Column(name = "NoticeFlag", length = 1)
	@Length(max = 1)
	public String getNoticeFlag() {
		return this.noticeFlag;
	}

	public void setNoticeFlag(String noticeFlag) {
		this.noticeFlag = noticeFlag;
	}

	@Column(name = "NoticeDate", length = 8)
	@Length(max = 8)
	public String getNoticeDate() {
		return this.noticeDate;
	}

	public void setNoticeDate(String noticeDate) {
		this.noticeDate = noticeDate;
	}

	@Column(name = "ARBDate", length = 8)
	@Length(max = 8)
	public String getArdate() {
		return this.ardate;
	}

	public void setArdate(String ardate) {
		this.ardate = ardate;
	}

	@Column(name = "HitsDate", length = 8)
	@Length(max = 8)
	public String getHitsDate() {
		return this.hitsDate;
	}

	public void setHitsDate(String hitsDate) {
		this.hitsDate = hitsDate;
	}

	@Column(name = "HitsValue")
	public Short getHitsValue() {
		return this.hitsValue;
	}

	public void setHitsValue(Short hitsValue) {
		this.hitsValue = hitsValue;
	}

	@Column(name = "MultiAgentFlag", length = 1)
	@Length(max = 1)
	public String getMultiAgentFlag() {
		return this.multiAgentFlag;
	}

	public void setMultiAgentFlag(String multiAgentFlag) {
		this.multiAgentFlag = multiAgentFlag;
	}

	@Column(name = "ParcelNumber", length = 23)
	@Length(max = 23)
	public String getParcelNumber() {
		return this.parcelNumber;
	}

	public void setParcelNumber(String parcelNumber) {
		this.parcelNumber = parcelNumber;
	}

	@Column(name = "StateCatCode", length = 2)
	@Length(max = 2)
	public String getStateCatCode() {
		return this.stateCatCode;
	}

	public void setStateCatCode(String stateCatCode) {
		this.stateCatCode = stateCatCode;
	}

	@Column(name = "PPTCode", length = 2)
	@Length(max = 2)
	public String getPptcode() {
		return this.pptcode;
	}

	public void setPptcode(String pptcode) {
		this.pptcode = pptcode;
	}

	@Column(name = "SICCode", length = 5)
	@Length(max = 5)
	public String getSiccode() {
		return this.siccode;
	}

	public void setSiccode(String siccode) {
		this.siccode = siccode;
	}

	@Column(name = "ICCode", length = 1)
	@Length(max = 1)
	public String getIccode() {
		return this.iccode;
	}

	public void setIccode(String iccode) {
		this.iccode = iccode;
	}

	@Column(name = "RegionCenter", length = 2)
	@Length(max = 2)
	public String getRegionCenter() {
		return this.regionCenter;
	}

	public void setRegionCenter(String regionCenter) {
		this.regionCenter = regionCenter;
	}

	@Column(name = "MapFacet", length = 7)
	@Length(max = 7)
	public String getMapFacet() {
		return this.mapFacet;
	}

	public void setMapFacet(String mapFacet) {
		this.mapFacet = mapFacet;
	}

	@Column(name = "PersPropValue")
	public Short getPersPropValue() {
		return this.persPropValue;
	}

	public void setPersPropValue(Short persPropValue) {
		this.persPropValue = persPropValue;
	}

	@Column(name = "LandValue")
	public Integer getLandValue() {
		return this.landValue;
	}

	public void setLandValue(Integer landValue) {
		this.landValue = landValue;
	}

	@Column(name = "ImprovementsValue")
	public Integer getImprovementsValue() {
		return this.improvementsValue;
	}

	public void setImprovementsValue(Integer improvementsValue) {
		this.improvementsValue = improvementsValue;
	}

	@Column(name = "ProductivityValue")
	public Integer getProductivityValue() {
		return this.productivityValue;
	}

	public void setProductivityValue(Integer productivityValue) {
		this.productivityValue = productivityValue;
	}

	@Column(name = "ProductivityType", length = 1)
	@Length(max = 1)
	public String getProductivityType() {
		return this.productivityType;
	}

	public void setProductivityType(String productivityType) {
		this.productivityType = productivityType;
	}

	@Column(name = "SpecialCode", length = 1)
	@Length(max = 1)
	public String getSpecialCode() {
		return this.specialCode;
	}

	public void setSpecialCode(String specialCode) {
		this.specialCode = specialCode;
	}

	@Column(name = "HMSTDXMPTCode", length = 1)
	@Length(max = 1)
	public String getHmstdxmptcode() {
		return this.hmstdxmptcode;
	}

	public void setHmstdxmptcode(String hmstdxmptcode) {
		this.hmstdxmptcode = hmstdxmptcode;
	}

	@Column(name = "PctHMSTDValue")
	public Short getPctHmstdvalue() {
		return this.pctHmstdvalue;
	}

	public void setPctHmstdvalue(Short pctHmstdvalue) {
		this.pctHmstdvalue = pctHmstdvalue;
	}

	@Column(name = "VetPCT1")
	public Short getVetPct1() {
		return this.vetPct1;
	}

	public void setVetPct1(Short vetPct1) {
		this.vetPct1 = vetPct1;
	}

	@Column(name = "VetPCT2")
	public Short getVetPct2() {
		return this.vetPct2;
	}

	public void setVetPct2(Short vetPct2) {
		this.vetPct2 = vetPct2;
	}

	@Column(name = "SPCLXMPTCode", length = 1)
	@Length(max = 1)
	public String getSpclxmptcode() {
		return this.spclxmptcode;
	}

	public void setSpclxmptcode(String spclxmptcode) {
		this.spclxmptcode = spclxmptcode;
	}

	@Column(name = "SPCLXMPTValue")
	public Integer getSpclxmptvalue() {
		return this.spclxmptvalue;
	}

	public void setSpclxmptvalue(Integer spclxmptvalue) {
		this.spclxmptvalue = spclxmptvalue;
	}

	@Column(name = "SPCLXMPTPCT", length = 3)
	@Length(max = 3)
	public String getSpclxmptpct() {
		return this.spclxmptpct;
	}

	public void setSpclxmptpct(String spclxmptpct) {
		this.spclxmptpct = spclxmptpct;
	}

	@Column(name = "HTSFlag", length = 1)
	@Length(max = 1)
	public String getHtsflag() {
		return this.htsflag;
	}

	public void setHtsflag(String htsflag) {
		this.htsflag = htsflag;
	}

	@Column(name = "PTSFlag", length = 1)
	@Length(max = 1)
	public String getPtsflag() {
		return this.ptsflag;
	}

	public void setPtsflag(String ptsflag) {
		this.ptsflag = ptsflag;
	}

	@Column(name = "BPSFlag", length = 1)
	@Length(max = 1)
	public String getBpsflag() {
		return this.bpsflag;
	}

	public void setBpsflag(String bpsflag) {
		this.bpsflag = bpsflag;
	}

	@Column(name = "RealPropRef", length = 13)
	@Length(max = 13)
	public String getRealPropRef() {
		return this.realPropRef;
	}

	public void setRealPropRef(String realPropRef) {
		this.realPropRef = realPropRef;
	}

	@Column(name = "ExemptValue")
	public Integer getExemptValue() {
		return this.exemptValue;
	}

	public void setExemptValue(Integer exemptValue) {
		this.exemptValue = exemptValue;
	}

	@Column(name = "TaxableValue")
	public Integer getTaxableValue() {
		return this.taxableValue;
	}

	public void setTaxableValue(Integer taxableValue) {
		this.taxableValue = taxableValue;
	}

	@Column(name = "ADJCADCode", length = 3)
	@Length(max = 3)
	public String getAdjcadcode() {
		return this.adjcadcode;
	}

	public void setAdjcadcode(String adjcadcode) {
		this.adjcadcode = adjcadcode;
	}

	@Column(name = "ADJCADAcct", length = 10)
	@Length(max = 10)
	public String getAdjcadacct() {
		return this.adjcadacct;
	}

	public void setAdjcadacct(String adjcadacct) {
		this.adjcadacct = adjcadacct;
	}

	@Column(name = "ADJCADLandValue")
	public Short getAdjcadlandValue() {
		return this.adjcadlandValue;
	}

	public void setAdjcadlandValue(Short adjcadlandValue) {
		this.adjcadlandValue = adjcadlandValue;
	}

	@Column(name = "ADJCADIMPRValue")
	public Short getAdjcadimprvalue() {
		return this.adjcadimprvalue;
	}

	public void setAdjcadimprvalue(Short adjcadimprvalue) {
		this.adjcadimprvalue = adjcadimprvalue;
	}

	@Column(name = "ADJCADPersValue")
	public Short getAdjcadpersValue() {
		return this.adjcadpersValue;
	}

	public void setAdjcadpersValue(Short adjcadpersValue) {
		this.adjcadpersValue = adjcadpersValue;
	}

	@Column(name = "NBHD", length = 5)
	@Length(max = 5)
	public String getNbhd() {
		return this.nbhd;
	}

	public void setNbhd(String nbhd) {
		this.nbhd = nbhd;
	}

	@Column(name = "LUC", length = 3)
	@Length(max = 3)
	public String getLuc() {
		return this.luc;
	}

	public void setLuc(String luc) {
		this.luc = luc;
	}

	@Column(name = "AgentNum", length = 5)
	@Length(max = 5)
	public String getAgentNum() {
		return this.agentNum;
	}

	public void setAgentNum(String agentNum) {
		this.agentNum = agentNum;
	}

	@Column(name = "AgentAddr1", length = 26)
	@Length(max = 26)
	public String getAgentAddr1() {
		return this.agentAddr1;
	}

	public void setAgentAddr1(String agentAddr1) {
		this.agentAddr1 = agentAddr1;
	}

	@Column(name = "MKTLandValue")
	public Short getMktlandValue() {
		return this.mktlandValue;
	}

	public void setMktlandValue(Short mktlandValue) {
		this.mktlandValue = mktlandValue;
	}

	@Column(name = "MKTIMPRValue")
	public Short getMktimprvalue() {
		return this.mktimprvalue;
	}

	public void setMktimprvalue(Short mktimprvalue) {
		this.mktimprvalue = mktimprvalue;
	}

	@Column(name = "RendFlag", length = 1)
	@Length(max = 1)
	public String getRendFlag() {
		return this.rendFlag;
	}

	public void setRendFlag(String rendFlag) {
		this.rendFlag = rendFlag;
	}

	@Column(name = "CAMAMktValue")
	public Short getCamamktValue() {
		return this.camamktValue;
	}

	public void setCamamktValue(Short camamktValue) {
		this.camamktValue = camamktValue;
	}

	@Column(name = "LSTVisitDate", length = 8)
	@Length(max = 8)
	public String getLstvisitDate() {
		return this.lstvisitDate;
	}

	public void setLstvisitDate(String lstvisitDate) {
		this.lstvisitDate = lstvisitDate;
	}

	@Column(name = "ActualPURDate", length = 8)
	@Length(max = 8)
	public String getActualPurdate() {
		return this.actualPurdate;
	}

	public void setActualPurdate(String actualPurdate) {
		this.actualPurdate = actualPurdate;
	}

	@Column(name = "EffectPURDate", length = 8)
	@Length(max = 8)
	public String getEffectPurdate() {
		return this.effectPurdate;
	}

	public void setEffectPurdate(String effectPurdate) {
		this.effectPurdate = effectPurdate;
	}

}
