package com.westchase.persistence.model;
// Generated Jun 29, 2009 7:29:18 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * MapnoId generated by hbm2java
 */
@Embeddable
public class MapnoId implements java.io.Serializable {

	private Integer personId;
	private String mapNo;
	private String hcad;
	private Date inputDate;

	public MapnoId() {
	}

	public MapnoId(Integer personId, String mapNo, String hcad, Date inputDate) {
		this.personId = personId;
		this.mapNo = mapNo;
		this.hcad = hcad;
		this.inputDate = inputDate;
	}

	@Column(name = "PersonId")
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "MapNo", length = 50)
	@Length(max = 50)
	public String getMapNo() {
		return this.mapNo;
	}

	public void setMapNo(String mapNo) {
		this.mapNo = mapNo;
	}

	@Column(name = "HCAD", length = 50)
	@Length(max = 50)
	public String getHcad() {
		return this.hcad;
	}

	public void setHcad(String hcad) {
		this.hcad = hcad;
	}

	@Column(name = "InputDate", length = 19)
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MapnoId))
			return false;
		MapnoId castOther = (MapnoId) other;

		return ((this.getPersonId() == castOther.getPersonId()) || (this
				.getPersonId() != null
				&& castOther.getPersonId() != null && this.getPersonId()
				.equals(castOther.getPersonId())))
				&& ((this.getMapNo() == castOther.getMapNo()) || (this
						.getMapNo() != null
						&& castOther.getMapNo() != null && this.getMapNo()
						.equals(castOther.getMapNo())))
				&& ((this.getHcad() == castOther.getHcad()) || (this.getHcad() != null
						&& castOther.getHcad() != null && this.getHcad()
						.equals(castOther.getHcad())))
				&& ((this.getInputDate() == castOther.getInputDate()) || (this
						.getInputDate() != null
						&& castOther.getInputDate() != null && this
						.getInputDate().equals(castOther.getInputDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPersonId() == null ? 0 : this.getPersonId().hashCode());
		result = 37 * result
				+ (getMapNo() == null ? 0 : this.getMapNo().hashCode());
		result = 37 * result
				+ (getHcad() == null ? 0 : this.getHcad().hashCode());
		result = 37 * result
				+ (getInputDate() == null ? 0 : this.getInputDate().hashCode());
		return result;
	}

}
