package com.westchase.persistence.model;
// Generated Jun 29, 2009 7:29:18 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mapno generated by hbm2java
 */
@Entity
@Table(name = "mapno")
public class Mapno implements java.io.Serializable {

	private MapnoId id;

	public Mapno() {
	}

	public Mapno(MapnoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "personId", column = @Column(name = "PersonId")),
			@AttributeOverride(name = "mapNo", column = @Column(name = "MapNo", length = 50)),
			@AttributeOverride(name = "hcad", column = @Column(name = "HCAD", length = 50)),
			@AttributeOverride(name = "inputDate", column = @Column(name = "InputDate", length = 19))})
	public MapnoId getId() {
		return this.id;
	}

	public void setId(MapnoId id) {
		this.id = id;
	}

}
