package com.westchase.persistence.model;
// Generated Jun 29, 2009 7:29:18 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Naics generated by hbm2java
 */
@Entity
@Table(name = "naics")
public class Naics implements java.io.Serializable {

	private String code;
	private String description;

	public Naics() {
	}

	public Naics(String code) {
		this.code = code;
	}
	public Naics(String code, String description) {
		this.code = code;
		this.description = description;
	}

	@Id
	@Column(name = "Code", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "Description", length = 75)
	@Length(max = 75)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
