package com.westchase.persistence.model;

// Generated Nov 14, 2012 9:29:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Officer generated by hbm2java
 */
@Entity
@Table(name = "officer")
public class Officer implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private Integer badge;
	private String cellPhone;
	private boolean active;
	private Set<PatrolActivity> patrolActivities = new HashSet<PatrolActivity>(0);
	private Set<PatrolActivityOfficer> patrolActivityOfficers = new HashSet<PatrolActivityOfficer>(0);

	public Officer() {
	}
	
	public Officer(Integer id) {
		this();
		setId(id);
	}

	public Officer(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Officer(String firstName, String lastName, Integer badge, String cellPhone, Set<PatrolActivity> patrolActivities) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.badge = badge;
		this.patrolActivities = patrolActivities;
		this.cellPhone = cellPhone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "badge")
	public Integer getBadge() {
		return this.badge;
	}

	public void setBadge(Integer badge) {
		this.badge = badge;
	}

	@Column(name = "cell_phone", nullable = false)
	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "officer")
	public Set<PatrolActivity> getPatrolActivities() {
		return this.patrolActivities;
	}

	public void setPatrolActivities(Set<PatrolActivity> patrolActivities) {
		this.patrolActivities = patrolActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "officer")
	public Set<PatrolActivityOfficer> getPatrolActivityOfficers() {
		return this.patrolActivityOfficers;
	}

	public void setPatrolActivityOfficers(Set<PatrolActivityOfficer> patrolActivityOfficers) {
		this.patrolActivityOfficers = patrolActivityOfficers;
	}
	
	@Transient
	public String getFullName() {
		return firstName + " " + lastName;
	}
	
	@Transient
	public String getFullNameReverse() {
		return lastName + ", " + firstName;
	}

	@Column(name = "active")
	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
