package com.westchase.persistence.model;

// Generated Nov 14, 2012 9:29:30 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatrolActivityDetail generated by hbm2java
 */
@Entity
@Table(name = "patrol_activity_detail")
public class PatrolActivityDetail implements java.io.Serializable {

	private Long id;
	private Property property;
	private PatrolDetailCategory patrolDetailCategory;
	private PatrolActivity patrolActivity;
	private PatrolDetailType patrolDetailType;
	private Date receivedDateTime;
	private Date arrivedDateTime;
	private Date clearedDateTime;
	private String officerRole;
	private String disposition;
	private String incidentId;
	private String locationDesc;
	private String comments;
	private Set<PatrolActivityDetailCitizen> patrolActivityDetailCitizens = new HashSet<PatrolActivityDetailCitizen>(0);

	public PatrolActivityDetail() {
	}

	public PatrolActivityDetail(PatrolDetailCategory patrolDetailCategory, PatrolActivity patrolActivity,
			PatrolDetailType patrolDetailType, String comments) {
		this.patrolDetailCategory = patrolDetailCategory;
		this.patrolActivity = patrolActivity;
		this.patrolDetailType = patrolDetailType;
		this.comments = comments;
	}

	public PatrolActivityDetail(Property property, PatrolDetailCategory patrolDetailCategory,
			PatrolActivity patrolActivity, PatrolDetailType patrolDetailType, Date receivedDateTime, Date arrivedDateTime,
			Date clearedDateTime, String officerRole, String disposition, String incidentId, String locationDesc,
			String comments, Set<PatrolActivityDetailCitizen> patrolActivityDetailCitizens) {
		this.property = property;
		this.patrolDetailCategory = patrolDetailCategory;
		this.patrolActivity = patrolActivity;
		this.patrolDetailType = patrolDetailType;
		this.receivedDateTime = receivedDateTime;
		this.arrivedDateTime = arrivedDateTime;
		this.clearedDateTime = clearedDateTime;
		this.officerRole = officerRole;
		this.disposition = disposition;
		this.incidentId = incidentId;
		this.locationDesc = locationDesc;
		this.comments = comments;
		this.patrolActivityDetailCitizens = patrolActivityDetailCitizens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "location_property_id")
	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patrol_detail_category_id", nullable = false)
	public PatrolDetailCategory getPatrolDetailCategory() {
		return this.patrolDetailCategory;
	}

	public void setPatrolDetailCategory(PatrolDetailCategory patrolDetailCategory) {
		this.patrolDetailCategory = patrolDetailCategory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patrol_activity_id", nullable = false)
	public PatrolActivity getPatrolActivity() {
		return this.patrolActivity;
	}

	public void setPatrolActivity(PatrolActivity patrolActivity) {
		this.patrolActivity = patrolActivity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patrol_detail_type_id", nullable = false)
	public PatrolDetailType getPatrolDetailType() {
		return this.patrolDetailType;
	}

	public void setPatrolDetailType(PatrolDetailType patrolDetailType) {
		this.patrolDetailType = patrolDetailType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_date_time")
	public Date getReceivedDateTime() {
		return this.receivedDateTime;
	}

	public void setReceivedDateTime(Date receivedDateTime) {
		this.receivedDateTime = receivedDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrived_date_time")
	public Date getArrivedDateTime() {
		return this.arrivedDateTime;
	}

	public void setArrivedDateTime(Date arrivedDateTime) {
		this.arrivedDateTime = arrivedDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cleared_date_time")
	public Date getClearedDateTime() {
		return this.clearedDateTime;
	}

	public void setClearedDateTime(Date clearedDateTime) {
		this.clearedDateTime = clearedDateTime;
	}

	@Column(name = "officer_role", length = 9)
	public String getOfficerRole() {
		return this.officerRole;
	}

	public void setOfficerRole(String officerRole) {
		this.officerRole = officerRole;
	}

	@Column(name = "disposition")
	public String getDisposition() {
		return this.disposition;
	}

	public void setDisposition(String disposition) {
		this.disposition = disposition;
	}

	@Column(name = "incident_id")
	public String getIncidentId() {
		return this.incidentId;
	}

	public void setIncidentId(String incidentId) {
		this.incidentId = incidentId;
	}

	@Column(name = "location_desc")
	public String getLocationDesc() {
		return this.locationDesc;
	}

	public void setLocationDesc(String locationDesc) {
		this.locationDesc = locationDesc;
	}

	@Column(name = "comments", nullable = false)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patrolActivityDetail")
	public Set<PatrolActivityDetailCitizen> getPatrolActivityDetailCitizens() {
		return this.patrolActivityDetailCitizens;
	}

	public void setPatrolActivityDetailCitizens(Set<PatrolActivityDetailCitizen> patrolActivityDetailCitizens) {
		this.patrolActivityDetailCitizens = patrolActivityDetailCitizens;
	}

}
