package com.westchase.persistence.model;

// Generated Nov 14, 2012 9:29:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatrolActivityDetailCitizen generated by hbm2java
 */
@Entity
@Table(name = "patrol_activity_detail_citizen")
public class PatrolActivityDetailCitizen implements java.io.Serializable {

	private long id;
	private Citizen citizen;
	private PatrolActivityDetail patrolActivityDetail;

	public PatrolActivityDetailCitizen() {
	}

	public PatrolActivityDetailCitizen(long id, Citizen citizen, PatrolActivityDetail patrolActivityDetail) {
		this.id = id;
		this.citizen = citizen;
		this.patrolActivityDetail = patrolActivityDetail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "citizen_id", nullable = false)
	public Citizen getCitizen() {
		return this.citizen;
	}

	public void setCitizen(Citizen citizen) {
		this.citizen = citizen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patrol_activity_detail_id", nullable = false)
	public PatrolActivityDetail getPatrolActivityDetail() {
		return this.patrolActivityDetail;
	}

	public void setPatrolActivityDetail(PatrolActivityDetail patrolActivityDetail) {
		this.patrolActivityDetail = patrolActivityDetail;
	}

}
