package com.westchase.persistence.model;

// Generated Nov 14, 2012 9:29:30 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PatrolDetailType generated by hbm2java
 */
@Entity
@Table(name = "patrol_detail_type")
public class PatrolDetailType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<PatrolActivityDetail> patrolActivityDetails = new HashSet<PatrolActivityDetail>(0);

	public PatrolDetailType() {
	}

	public PatrolDetailType(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	public PatrolDetailType(Integer id, String name, Set<PatrolActivityDetail> patrolActivityDetails) {
		this.id = id;
		this.name = name;
		this.patrolActivityDetails = patrolActivityDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patrolDetailType")
	public Set<PatrolActivityDetail> getPatrolActivityDetails() {
		return this.patrolActivityDetails;
	}

	public void setPatrolActivityDetails(Set<PatrolActivityDetail> patrolActivityDetails) {
		this.patrolActivityDetails = patrolActivityDetails;
	}
	
	@Transient
	public String getSummaryString() {
		return this.id + " - " + this.name;
	}
	public void setSummaryString(String summaryString) {}

}
