package com.westchase.persistence.model;

// Generated Nov 22, 2014 10:11:45 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatrolActivityOfficer generated by hbm2java
 */
@Entity
@Table(name = "patrol_activity_officer")
public class PatrolActivityOfficer implements java.io.Serializable {

	private Long id;
	private PatrolActivity patrolActivity;
	private Officer officer;

	public PatrolActivityOfficer() {
	}

	public PatrolActivityOfficer(PatrolActivity patrolActivity, Officer officer) {
		this.patrolActivity = patrolActivity;
		this.officer = officer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patrol_activity_id", nullable = false)
	public PatrolActivity getPatrolActivity() {
		return this.patrolActivity;
	}

	public void setPatrolActivity(PatrolActivity patrolActivity) {
		this.patrolActivity = patrolActivity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "officer_id", nullable = false)
	public Officer getOfficer() {
		return this.officer;
	}

	public void setOfficer(Officer officer) {
		this.officer = officer;
	}

}
