package com.westchase.persistence.model;

// Generated Nov 6, 2013 5:48:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatrolActivityHotspot generated by hbm2java
 */
@Entity
@Table(name = "patrol_activity_hotspot")
public class PatrolActivityHotspot implements java.io.Serializable {

	private Integer id;
	private PatrolActivity patrolActivity;
	private PatrolHotspot patrolHotspot;

	public PatrolActivityHotspot() {
	}

	public PatrolActivityHotspot(PatrolActivity patrolActivity, PatrolHotspot patrolHotspot) {
		this.patrolActivity = patrolActivity;
		this.patrolHotspot = patrolHotspot;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patrol_activity_id", nullable = false)
	public PatrolActivity getPatrolActivity() {
		return this.patrolActivity;
	}

	public void setPatrolActivity(PatrolActivity patrolActivity) {
		this.patrolActivity = patrolActivity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hotspot_id", nullable = false)
	public PatrolHotspot getPatrolHotspot() {
		return this.patrolHotspot;
	}

	public void setPatrolHotspot(PatrolHotspot patrolHotspot) {
		this.patrolHotspot = patrolHotspot;
	}

}
