package com.westchase.persistence.model;

// Generated Nov 6, 2013 5:48:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PatrolHotspot generated by hbm2java
 */
@Entity
@Table(name = "patrol_hotspot")
public class PatrolHotspot implements java.io.Serializable {

	private Integer id;
	private String mapno;
	private String name;
	private boolean eastWest;
	private Set<PatrolActivityHotspot> patrolActivityHotspots = new HashSet<PatrolActivityHotspot>(0);

	public PatrolHotspot() {
		super();
	}

	public PatrolHotspot(Integer id) {
		this();
		this.id = id;
	}

	public PatrolHotspot(String mapno, String name, boolean eastWest) {
		this();
		this.mapno = mapno;
		this.name = name;
		this.eastWest = eastWest;
	}

	public PatrolHotspot(String mapno, String name, boolean eastWest, Set<PatrolActivityHotspot> patrolActivityHotspots) {
		this();
		this.mapno = mapno;
		this.name = name;
		this.eastWest = eastWest;
		this.patrolActivityHotspots = patrolActivityHotspots;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mapno", nullable = false, length = 45)
	public String getMapno() {
		return this.mapno;
	}

	public void setMapno(String mapno) {
		this.mapno = mapno;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "east_west", nullable = false)
	public boolean isEastWest() {
		return this.eastWest;
	}

	public void setEastWest(boolean eastWest) {
		this.eastWest = eastWest;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patrolHotspot")
	public Set<PatrolActivityHotspot> getPatrolActivityHotspots() {
		return this.patrolActivityHotspots;
	}

	public void setPatrolActivityHotspots(Set<PatrolActivityHotspot> patrolActivityHotspots) {
		this.patrolActivityHotspots = patrolActivityHotspots;
	}

	@Transient
	public String getSummaryString() {
		return this.name + " [" + this.mapno + "]";
	}
	public void setSummaryString(String summaryString) {}	
	
}
