package com.westchase.persistence.model;

// Generated Nov 14, 2012 9:29:30 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PatrolType generated by hbm2java
 */
@Entity
@Table(name = "patrol_type")
public class PatrolType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer orderVal;
	private Set<PatrolActivity> patrolActivities = new HashSet<PatrolActivity>(0);

	public PatrolType() {
	}

	public PatrolType(String name, Set<PatrolActivity> patrolActivities) {
		this.name = name;
		this.patrolActivities = patrolActivities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "order_val")
	public Integer getOrderVal() {
		return this.orderVal;
	}

	public void setOrderVal(Integer orderVal) {
		this.orderVal = orderVal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patrolType")
	public Set<PatrolActivity> getPatrolActivities() {
		return this.patrolActivities;
	}

	public void setPatrolActivities(Set<PatrolActivity> patrolActivities) {
		this.patrolActivities = patrolActivities;
	}

}
