package com.westchase.persistence.model;

// Generated May 26, 2010 7:54:28 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhoneBookRelation generated by hbm2java
 */
@Entity
@Table(name = "phone_book_relation")
public class PhoneBookRelation implements java.io.Serializable {

	private Long id;
	private Property property;
	private PhoneBookRelationType phoneBookRelationType;
	private PhoneBook phoneBook;

	public PhoneBookRelation() {
	}

	public PhoneBookRelation(Property property, PhoneBookRelationType phoneBookRelationType, PhoneBook phoneBook) {
		this.property = property;
		this.phoneBookRelationType = phoneBookRelationType;
		this.phoneBook = phoneBook;
	}

	public PhoneBookRelation(Long id) {
		this.id = id;
	}

	public PhoneBookRelation(PhoneBook phoneBook, Property property, PhoneBookRelationType phoneBookRelationType) {
		this.phoneBook = phoneBook;
		this.property = property;
		this.phoneBookRelationType = phoneBookRelationType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "property", nullable = false)
	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "relation_type", nullable = false)
	public PhoneBookRelationType getPhoneBookRelationType() {
		return this.phoneBookRelationType;
	}

	public void setPhoneBookRelationType(PhoneBookRelationType phoneBookRelationType) {
		this.phoneBookRelationType = phoneBookRelationType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "phone_book", nullable = false)
	public PhoneBook getPhoneBook() {
		return this.phoneBook;
	}

	public void setPhoneBook(PhoneBook phoneBook) {
		this.phoneBook = phoneBook;
	}

}
