package com.westchase.persistence.model;

// Generated Oct 15, 2009 6:09:28 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhoneBookProperty generated by hbm2java
 */
@Entity
@Table(name = "phone_book_property")
public class PhoneBookProperty implements java.io.Serializable {

	private Integer id;
	private Property property;
	private PhoneBook phoneBook;
	private String suiteNumber;

	public PhoneBookProperty() {
	}

	public PhoneBookProperty(Property property, PhoneBook phoneBook, String suiteNumber) {
		this.property = property;
		this.phoneBook = phoneBook;
		this.suiteNumber = suiteNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "property", nullable = false)
	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "phone_book", nullable = false)
	public PhoneBook getPhoneBook() {
		return this.phoneBook;
	}

	public void setPhoneBook(PhoneBook phoneBook) {
		this.phoneBook = phoneBook;
	}

	@Column(name = "suite_number", nullable = true, length = 45)
	public String getSuiteNumber() {
		return this.suiteNumber;
	}

	public void setSuiteNumber(String suiteNumber) {
		this.suiteNumber = suiteNumber;
	}

}
