package com.westchase.persistence.model;

// Generated Oct 8, 2012 6:19:31 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhoneBookMonumentSignNumber generated by hbm2java
 */
@Entity
@Table(name = "phone_book_monument_sign_number")
public class PhoneBookMonumentSignNumber implements java.io.Serializable {

	private Integer id;
	private PhoneBook phoneBook;
	private int monumentSign;

	public PhoneBookMonumentSignNumber() {
	}

	public PhoneBookMonumentSignNumber(PhoneBook phoneBook, int monumentSign) {
		this.phoneBook = phoneBook;
		this.monumentSign = monumentSign;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "phone_book_id", nullable = false)
	public PhoneBook getPhoneBook() {
		return this.phoneBook;
	}

	public void setPhoneBook(PhoneBook phoneBook) {
		this.phoneBook = phoneBook;
	}

	@Column(name = "monument_sign", nullable = false)
	public int getMonumentSign() {
		return this.monumentSign;
	}

	public void setMonumentSign(int monumentSign) {
		this.monumentSign = monumentSign;
	}

}
