package com.westchase.persistence.model;

// Generated May 26, 2010 7:54:28 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhoneBookRelationType generated by hbm2java
 */
@Entity
@Table(name = "phone_book_relation_type")
public class PhoneBookRelationType implements java.io.Serializable {

	private int id;
	private String name;
	private Set<PhoneBookRelation> phoneBookRelations = new HashSet<PhoneBookRelation>(0);

	public PhoneBookRelationType() {
	}

	public PhoneBookRelationType(int id) {
		this.id = id;
	}

	public PhoneBookRelationType(String name) {
		this.name = name;
	}

	public PhoneBookRelationType(String name, Set<PhoneBookRelation> phoneBookRelations) {
		this.name = name;
		this.phoneBookRelations = phoneBookRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phoneBookRelationType")
	public Set<PhoneBookRelation> getPhoneBookRelations() {
		return this.phoneBookRelations;
	}

	public void setPhoneBookRelations(Set<PhoneBookRelation> phoneBookRelations) {
		this.phoneBookRelations = phoneBookRelations;
	}

}
