package com.westchase.persistence.model;
// Generated Jun 29, 2009 7:29:18 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * PersonCategory generated by hbm2java
 */
@Entity
@Table(name = "phone_book_category")
public class PhoneBookCategory implements java.io.Serializable {

	private Integer id;
	private PhoneBook phoneBook;
	private Category category;
	private Date inputDate;

	public PhoneBookCategory() {
	}

	public PhoneBookCategory(Category category) {
		this.category = category;
	}
	public PhoneBookCategory(PhoneBook phoneBook, Category category, Date inputDate) {
		this.phoneBook = phoneBook;
		this.category = category;
		this.inputDate = inputDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PhoneBookId", nullable = false)
	@NotNull
	public PhoneBook getPhoneBook() {
		return this.phoneBook;
	}

	public void setPhoneBook(PhoneBook phoneBook) {
		this.phoneBook = phoneBook;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CategoryCode", nullable = false)
	@NotNull
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InputDate", length = 19)
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

}
