package com.westchase.persistence.model;

// Generated Sep 16, 2009 6:36:46 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhoneBook generated by hbm2java
 */
@Entity
@Table(name = "phone_book")
public class PhoneBook implements java.io.Serializable {

	private Integer id;
	private Company company;
	private String title;
	private String firstName;
	private String middleInitial;
	private String lastName;
	private String salutation;
	private String suffix;
	private String jobTitle;
	private String companyName;
	private String department;
	private String wkPhone;
	private String wkext;
	private String directPhone;
	private String faxPhone;
	private String mobilePhone;
	private String gender;
	private String email;
	private String altEmail;
	private boolean dontEmail;
	private String homeAddress;
	private String homePhone;
	private String homeFax;
	private boolean investor;
	private boolean westchaseToday;
	private String other;
	private String notes;
	private Date inputDate;
	private Date lastupdate;
	private Set<PhoneBookCategory> phoneBookCategories = new HashSet<PhoneBookCategory>(0);
	private Set<PhoneBookRelation> phoneBookRelations = new HashSet<PhoneBookRelation>(0);
	private Set<PhoneBookMonumentSignNumber> phoneBookMonumentSignNumbers = new HashSet<PhoneBookMonumentSignNumber>(0);

	public PhoneBook() {
	}

	public PhoneBook(Integer id) {
		this.id = id;
	}

	public PhoneBook(boolean dontEmail, boolean investor, boolean westchaseToday, Date lastupdate) {
		this.dontEmail = dontEmail;
		this.investor = investor;
		this.westchaseToday = westchaseToday;
		this.lastupdate = lastupdate;
	}

	public PhoneBook(Company company, String title, String firstName, String middleInitial, String lastName,
			String salutation, String suffix, String jobTitle, String company_1, String department, String wkPhone,
			String wkext, String faxPhone, String mobilePhone, String gender, String email, String altEmail, boolean dontEmail,
			String homeAddress, String homePhone, String homeFax, boolean investor, boolean westchaseToday,
			String other, String notes, Date inputDate, Date lastupdate, Set<PhoneBookCategory> phoneBookCategories,
			Set<PhoneBookRelation> phoneBookRelations) {
		this.company = company;
		this.title = title;
		this.firstName = firstName;
		this.middleInitial = middleInitial;
		this.lastName = lastName;
		this.salutation = salutation;
		this.suffix = suffix;
		this.jobTitle = jobTitle;
		this.companyName = company_1;
		this.department = department;
		this.wkPhone = wkPhone;
		this.wkext = wkext;
		this.faxPhone = faxPhone;
		this.mobilePhone = mobilePhone;
		this.gender = gender;
		this.email = email;
		this.altEmail = altEmail;
		this.dontEmail = dontEmail;
		this.homeAddress = homeAddress;
		this.homePhone = homePhone;
		this.homeFax = homeFax;
		this.investor = investor;
		this.westchaseToday = westchaseToday;
		this.other = other;
		this.notes = notes;
		this.inputDate = inputDate;
		this.lastupdate = lastupdate;
		this.phoneBookCategories = phoneBookCategories;
		this.phoneBookRelations = phoneBookRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CompanyId")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "Title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "FirstName", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MiddleInitial", length = 1)
	public String getMiddleInitial() {
		return this.middleInitial;
	}

	public void setMiddleInitial(String middleInitial) {
		this.middleInitial = middleInitial;
	}

	@Column(name = "LastName", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Salutation", length = 50)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "Suffix", length = 10)
	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	@Column(name = "JobTitle", length = 50)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "Company")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String company_1) {
		this.companyName = company_1;
	}

	@Column(name = "Department", length = 75)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "WkPhone", length = 50)
	public String getWkPhone() {
		return this.wkPhone;
	}

	public void setWkPhone(String wkPhone) {
		this.wkPhone = wkPhone;
	}

	@Column(name = "Wkext", length = 50)
	public String getWkext() {
		return this.wkext;
	}

	public void setWkext(String wkext) {
		this.wkext = wkext;
	}

	@Column(name = "DirectPhone", length = 50)
	public String getDirectPhone() {
		return directPhone;
	}

	public void setDirectPhone(String directPhone) {
		this.directPhone = directPhone;
	}

	@Column(name = "FaxPhone", length = 50)
	public String getFaxPhone() {
		return this.faxPhone;
	}

	public void setFaxPhone(String faxPhone) {
		this.faxPhone = faxPhone;
	}

	@Column(name = "MobilePhone", length = 50)
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "Gender", length = 7)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "Email", length = 255)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "AltEmail", length = 255)
	public String getAltEmail() {
		return this.altEmail;
	}

	public void setAltEmail(String altEmail) {
		this.altEmail = altEmail;
	}

	@Column(name = "DontEmail", nullable = false)
	public boolean isDontEmail() {
		return this.dontEmail;
	}

	public void setDontEmail(boolean dontEmail) {
		this.dontEmail = dontEmail;
	}

	@Column(name = "HomeAddress")
	public String getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	@Column(name = "HomePhone", length = 50)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "HomeFax", length = 50)
	public String getHomeFax() {
		return this.homeFax;
	}

	public void setHomeFax(String homeFax) {
		this.homeFax = homeFax;
	}

	@Column(name = "Investor", nullable = false)
	public boolean isInvestor() {
		return this.investor;
	}

	public void setInvestor(boolean investor) {
		this.investor = investor;
	}

	@Column(name = "WestchaseToday", nullable = false)
	public boolean isWestchaseToday() {
		return this.westchaseToday;
	}

	public void setWestchaseToday(boolean westchaseToday) {
		this.westchaseToday = westchaseToday;
	}

	@Column(name = "Other")
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@Column(name = "Notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InputDate", length = 19)
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdate", length = 19)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "phoneBook")
	public Set<PhoneBookCategory> getPhoneBookCategories() {
		return this.phoneBookCategories;
	}

	public void setPhoneBookCategories(Set<PhoneBookCategory> phoneBookCategories) {
		this.phoneBookCategories = phoneBookCategories;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "phoneBook")
	public Set<PhoneBookRelation> getPhoneBookRelations() {
		return this.phoneBookRelations;
	}

	public void setPhoneBookRelations(Set<PhoneBookRelation> phoneBookRelations) {
		this.phoneBookRelations = phoneBookRelations;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "phoneBook")
	public Set<PhoneBookMonumentSignNumber> getPhoneBookMonumentSignNumbers() {
		return this.phoneBookMonumentSignNumbers;
	}

	public void setPhoneBookMonumentSignNumbers(Set<PhoneBookMonumentSignNumber> phoneBookMonumentSignNumbers) {
		this.phoneBookMonumentSignNumbers = phoneBookMonumentSignNumbers;
	}

}
