package com.westchase.persistence.model;

// Generated Jan 19, 2014 12:27:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PropertyHcad generated by hbm2java
 */
@Entity
@Table(name = "property_hcad")
public class PropertyHcad implements java.io.Serializable {

	private Integer id;
	private Property property;
	private String hcad;
	private String notes;

	public PropertyHcad() {
	}

	public PropertyHcad(Property property, String hcad) {
		this.property = property;
		this.hcad = hcad;
	}

	public PropertyHcad(Property property, String hcad, String notes) {
		this.property = property;
		this.hcad = hcad;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "property_id", nullable = false)
	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	@Column(name = "hcad", nullable = false, length = 50)
	public String getHcad() {
		return this.hcad;
	}

	public void setHcad(String hcad) {
		this.hcad = hcad;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
