package com.westchase.persistence.model;

// Generated Apr 20, 2011 9:19:24 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PropertyType generated by hbm2java
 */
@Entity
@Table(name = "property_type")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class PropertyType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Property> properties = new HashSet<Property>(0);

	public PropertyType() {
	}

	public PropertyType(int id, String name) {
		this.id = new Integer(id);
		this.name = name;
	}

	public PropertyType(String name) {
		this.name = name;
	}

	public PropertyType(String name, Set<Property> properties) {
		this.name = name;
		this.properties = properties;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "propertyType")
	public Set<Property> getProperties() {
		return this.properties;
	}

	public void setProperties(Set<Property> properties) {
		this.properties = properties;
	}

}
